---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
     update_cache: yes
     state: latest

  - name: upgrade distribution
    apt:
      upgrade: yes
      state: latest

  - name: Install the apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: Add PHP suppport for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]
